cc_library(
  name = "mp_throw",
  hdrs = ["mp_throw.hpp"]
)

cc_binary(
  name = "mp_throw_test",
  srcs = ["mp_throw_test.cpp"],
  deps = ["mp_throw"]
  )

cc_binary(
  name = "nested_exception",
  srcs = ["nested_exception.cpp"],
  )


cc_binary(
  name = "point_example",
  srcs = ["point_example.cpp"],
  )

