cc_library(
  name = "any",
  hdrs = ["any.hpp"]
)

cc_binary(
  name = "forupto1",
  srcs = ["forupto1.cpp"]
)

cc_binary(
  name = "forupto3",
  srcs = ["forupto3.cpp"]
)

cc_binary(
  name = "any_test",
  srcs = ["any_test.cpp"],
  deps = [":any"]
)

cc_binary(
  name = "any_example",
  srcs = ["any_example.cpp"],
)

